<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DevDock.Core\DevDock.Core.csproj" />
    <ProjectReference Include="..\DevDock.Security\DevDock.Security.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
